### PR TITLE
Added AntiFloodPoints Enum

### PR DESCRIPTION
**Pull request by Bluscream**

### CODE REVIEW

**Comment by pathmann** [comment]
>The file ts3defines.py is still generated, so changes to the template files are missing.

The ts3defines module is meant to be a wrapper for all official ts3 plugin sdk constants. So where does this info come from?

**Comment by Bluscream** [comment]
The info is self tested and confirmed by 2 other persons that tested it. If you say ts3defines is not fitting, maybe i should place it in the ts3lib.py?

**Comment by pathmann** [comment]
I think the best fitting place would be the script where you use that info as I don't see that many use-cases for that.
Because this info is not extracted from the official plugin sdk it's horrible to maintain (hard to see changes from TeamSpeak Systems).

**Comment by Bluscream** [comment]
I see that it's not easy to maintain. Since i know you're very picky about what you accept i have a created my own little "common utils lib" bluscream.py. gonna drop it there then

**Comment by pathmann** [comment]
Creating a pypi package and adding that as dependency to your scripts would be another option.

**Comment by Bluscream** [comment]
I'm not quite sure if such a small package would get accepted by pythons package manager

**Comment by pathmann** [comment]
I'd guess pypi isn't checked at all (except automatically).

**Pull request closed without merging**
