### PR TITLE
Change objects to enums

### PR DESCRIPTION
**Pull request by Bluscream**
To simplify actions like getting the name by id for example https://stackoverflow.com/a/29880372

### CODE REVIEW

**Comment by pathmann** [comment]
The file ts3defines.py is still generated, so changes to the template files are missing.

logMessage is not the only ts3lib function using enums, so to make some sort of change and not break nearly every script, all affected functions need to be manually wrapped (a generic way might be the best solution).

**Comment by Bluscream** [comment]
Hmm. Maybe there's some way for scripts to locally create a enum from the class. So plugins can do that if they need iteration

**Comment by pathmann** [comment]
Something like this is a workaround, if you need some enum features ("locally"):
```python
AwayStatus = Enum('AwayStatus', {x: getattr(AwayStatus, x) for x in dir(AwayStatus) if not x.startswith("__")})```

Globally: this could break some things and I want pyTSon as close as possible to the original C SDK.

**Comment by Bluscream** [comment]
Thanks for showing a workaround, may others find this and be helped!

**Pull request closed without merging**
